### ISSUE TITLE
curl in cobalt

### ISSUE THREAD

**Issue by ghost** [Cobalt-OS/Cobalt#16]
Hi all.

I would like to know if it would be possible to run curl within the cobalt-os. *So... would it be possible to run curl within the cobalt operating system?*

**Comment by corbindavenport** [comment]
There is a port of curl to FreeDOS: https://gitlab.com/FreeDOS/net/curl

It needs networking drivers set up first though, which Cobalt doesn't currently have.

**Comment by ghost** [comment]
Hi corbindavenport, thank you for feedback.
