### ISSUE TITLE
Floppy Disc Emulation on Boot

### ISSUE THREAD

**Issue by ercanersoy** [Cobalt-OS/Cobalt#6]
I think Cobalt OS support computer that not supported El-Torito. CD image should boots with floppy disc emulation boot property. Therefore, ISO file doesn't necessary Syslinux.

**Comment by corbindavenport** [comment]
Cobalt OS doesn't really target extremely old PCs that normal FreeDOS does. But Cobalt uses the floppy emulation format of El-Torito, which works reliably on PCs from 1999 and older.

**Comment by ercanersoy** [comment]
I was open this ISO by 7-Zip. This ISO seems no emulation booting type.

![boot-no-emulation](https://cloud.githubusercontent.com/assets/15850068/16453945/59e18b9c-3e17-11e6-9361-0cf97a859299.png)
